#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Ken Terada s22C1088BT@s.chibakoudai.jp
# SPDX-License-Identifier: BSD-3-Clause

import sys

def tonum(s):
      try:
          return int(s)
      except:
          return float(s)


ans = 0
count = 0
ave = 0

for line in sys.stdin:
    line = line.rstrip()
    ans += tonum(line)
    count += 1

if  ans > 0
    ave = ans / count

print(ans)
print(ave)
